version: '3.8'

services:
  # Chrome desktop test
  playwright-chromium-desktop:
    build: .
    container_name: playwright_chromium_desktop
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/app
    working_dir: /app
    command: pytest test_site.py --browser chromium --device-type desktop --html=report.html

  # Firefox desktop test
  playwright-firefox-desktop:
    build: .
    container_name: playwright_firefox_desktop
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/app
    working_dir: /app
    command: pytest test_site.py --browser firefox --device-type desktop --html=report.html

  # Webkit desktop test
  playwright-webkit-desktop:
    build: .
    container_name: playwright_webkit_desktop
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/app
    working_dir: /app
    command: pytest test_site.py --browser webkit --device-type desktop --html=report.html

  # Chrome mobile test
  playwright-chromium-mobile:
    build: .
    container_name: playwright_chromium_mobile
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/app
    working_dir: /app
    command: pytest test_site.py --browser chromium --device-type mobile --html=report.html

  # Firefox mobile test
  playwright-firefox-mobile:
    build: .
    container_name: playwright_firefox_mobile
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/app
    working_dir: /app
    command: pytest test_site.py --browser firefox --device-type mobile --html=report.html

  # Webkit mobile test
  playwright-webkit-mobile:
    build: .
    container_name: playwright_webkit_mobile
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/app
    working_dir: /app
    command: pytest test_site.py --browser webkit --device-type mobile --html=report.html
